services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "5150:5150"      # Web UI and API
      - "8600:8600/udp"  # DNS
    command: "agent -dev -config-file=consul-service.json -client=0.0.0.0"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5150/v1/status/leader" ]
      interval: 30s      # Check every 30 seconds
      timeout: 10s       # Timeout after 10 seconds
      retries: 3         # Consider container unhealthy after 3 failures
      start_period: 30s  # Start checking after 30 seconds
    volumes:
      - ./consul-service.json:/consul-service.json
    networks:
      - consul-network

  kafka:
    image: docker.io/bitnami/kafka:3.8
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - consul-network

  spicedb:
    build:
      context: .
      dockerfile: config/spicedb/Dockerfile.spicedb
    ports:
      - "50051:50051"  # GRPC port
      - "8443:8443"    # HTTP port (secured with TLS)
    environment:
      - SPICEDB_LOG_LEVEL=debug
      - SPICEDB_GRPC_PRESHARED_KEY=spiceDBKey
      - SPICEDB_GRPC_TLS_CERT_PATH=/spicedb.crt
      - SPICEDB_GRPC_TLS_KEY_PATH=/spicedb.key
      - SPICEDB_HTTP_TLS_CERT_PATH=/spicedb.crt
      - SPICEDB_HTTP_TLS_KEY_PATH=/spicedb.key
      - SPICEDB_DATASTORE_ENGINE=postgres
      - SPICEDB_DATASTORE_CONN_URI=postgres://postgres:postgres@db:5432/spicedb?sslmode=disable
    depends_on:
      - db
    volumes:
      - ./config/spicedb/spicedb.crt:/spicedb.crt
      - ./config/spicedb/spicedb.key:/spicedb.key
    networks:
      - consul-network

  api-gateway:
    build:
      context: ./kontest-api-gateway
    container_name: api-gateway
    ports:
      - "5153:5153"  # Port for your Go service
    depends_on:
      consul:
        condition: service_healthy
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=5150
    networks:
      - consul-network

  kontest-api:
    build:
      context: ./kontest-api
    container_name: kontest-api
    ports:
      - "5151:5151"  # Port for your Go service
    depends_on:
      consul:
        condition: service_healthy
        
      db:
        condition: service_started
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=5150

      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres

      - KONTEST_API_SERVER_HOST=kontest-api
    networks:
      - consul-network

  kontest-user-stats-service:
    build:
      context: ./kontest-user-stats-service
    container_name: kontest-user-stats-service
    ports:
      - "5152:5152"  # Port for your Go service
    depends_on:
      consul:
        condition: service_healthy
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=5150

      - KONTEST_API_USER_STATS_SERVICE_HOST=kontest-user-stats-service
    networks:
      - consul-network

  kontest-email-service:
    build:
      context: ./kontest-email-service
    container_name: kontest-email-service
    ports:
      - "5157:5157"
    depends_on:
      consul:
        condition: service_healthy

      kafka:
        condition: service_started
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=5150

      - KONTEST_EMAIL_SERVICE_HOST=kontest-email-service

      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    networks:
      - consul-network
        
  kontest-authentication-service:
    build:
      context: ./kontest-authentication
    container_name: kontest-authentication-service
    ports:
      - "5155:5155"
    depends_on:
      consul:
        condition: service_healthy

      kafka:
        condition: service_started

      db:
        condition: service_started

      spicedb:
        condition: service_started

    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=5150

      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres

      - KONTEST_AUTHENTICATION_SERVICE_HOST=kontest-authentication-service

      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092

      - SPICEDB_HOST=spicedb
      - SPICEDB_PORT=50051
      - SPICEDB_TOKEN=spiceDBKey
      - SPICEDB_TLS_CERT_PATH=/spicedb.crt
    networks:
      - consul-network
    volumes:
      - ./config/spicedb/spicedb.crt:/spicedb.crt
  
  kontest-user-service:
    build:
      context: ./kontest-user-service
    container_name: kontest-user-service
    ports:
      - "5156:5156"
    depends_on:
      consul:
        condition: service_healthy
        
      db:
        condition: service_started

    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=5150

      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres

      - KONTEST_USER_SERVICE_HOST=kontest-user-service
      - KONTEST_USER_SERVICE_PORT=5156
    networks:
      - consul-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    networks:
      - consul-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/init-scripts/init-database-scripts:/docker-entrypoint-initdb.d

networks:
  consul-network:
    driver: bridge

volumes:
  db-data:
    driver: local

  kafka_data:
    driver: local